import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import localFont from "next/font/local";
//my own  font
const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//Next.js local bangla font use
export const FontBangla = localFont({
  src: "./../mayaboti-normal.ttf",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <nav className="w-11/12 mx-auto">
          <Navbar />
        </nav>
        <div className="py-2 md:w-11/12 mx-auto border-2 border-red-500">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
