import Products from "@/components/home/Products";
import React from "react";
//metadata ta use korle all products gele title ta change hoye jabe
export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};
const ProductRout = () => {
  return (
    <div>
      <Products />
    </div>
  );
};

export default ProductRout;
